server:
  port: 10200 # 8080  
spring:
  jackson:
    serialization.fail-on-empty-beans: false  
anagram:
  protocol: "http://"
  domain: "static.abscond.org"
  path: "/"
  file: "wordlist.txt"
local:
  protocol: "file://"
  domain: ""
  path: "/c:/workspace/anagram/src/main/resources/"
  file: "wordlist.txt"

  

